sudo: required
language: node_js
services:
  - docker
  - xvfb
node_js:
  - v8
  - v10
  - v12

## Missing dependency for Cypress https://github.com/cypress-io/cypress/issues/4069
addons:
  apt:
    packages:
    - libgconf-2-4

  
## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npm
    - ~/.cache

  override:
    # use the new "ci" command for fastest installs on CI
    - npm install
    - npm run all:deps-ci
    - npm run all:cy:verify

before_script:
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - npm run all:deps-ci
  - NODE_ENV=test npm run all:infra-start -- --silent &

script:
  - npm run all:test-ci

