
- task: CmdLine@2
  inputs:
    script: |
      docker run -it --rm \
          --env VERACODE_API_KEY_ID=$VERACODE_API_ID \
          --env VERACODE_API_KEY_SECRET=$VERACODE_API_KEY  \
          -v /host/os/path/to/myapp/:/myapp/ \
          veracode/pipeline-scan:cmd \
              -vid $VERACODE_API_KEY_ID -vkey $VERACODE_API_KEY_SECRET \
              --file /myapp/myapp.jar