trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/NodeGoat'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: docker run --tty --rm veracode/pipeline-scan:cmd  -vid $(VERACODE_API_KEY_ID) -vkey $(VERACODE_API_KEY_SECRET)  --file NodeGoat.zip\