trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:

    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
     docker run -it --rm \
    veracode/pipeline-scan:cmd \
        -vid $(VERACODE_API_KEY_ID) -vkey $(VERACODE_API_KEY_SECRET) \
        --file blah