trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:

    
- task: CmdLine@2
  inputs:
    script: |
      docker run --rm \
          --env VERACODE_API_KEY_ID=c2db7664... \
          --env VERACODE_API_KEY_SECRET=24f62c81... \
          -v /host/os/path/to/myapp/:/myapp/ \
          veracode/pipeline-scan:cmd \
              -vid $VERACODE_API_KEY_ID -vkey $VERACODE_API_KEY_SECRET \
              --file /myapp/myapp.jar