trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'jddintegrationtest'
    repository: 'veracode/pipeline-scan'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'