trigger: none

jobs:
- job: scanpythonapp
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      containerRegistry: 'jddintegrationtest'
      command: login
      
  - script: |
      docker run -it --rm \
     - zip myapp.zip ./src/
    - java -jar /opt/veracode/pipeline-scan.jar
        -vid $VERACODE_API_KEY_ID -vkey $VERACODE_API_KEY_SECRET
        --file myapp.zip