trigger: none

jobs:
- job: scanpythonapp
  workspace:
    clean: all
  pool:
    vmImage: 'veracode/pipeline-scan:latest'
  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      containerRegistry: 'jd200'
      command: login
      
  - script: |
      - zip myapp.zip ./src/
      - java -jar /opt/veracode/pipeline-scan.jar
        -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY
        --file myapp.zip